#*****************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# f37x-2025-05-08-15_38_07-250m-1core.tcl: Tcl script for re-creating project 'f37x-2025-05-08-15_38_07-250m-1core'
#
# Generated by Vivado on Fri May 09 14:22:15 CST 2025
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (f37x-2025-05-08-15_38_07-250m-1core.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/data/disk0/wrk/OpenTF/main/fpga/temp/f37x-2025-05-08-15_38_07-250m-1core/f37x-2025-05-08-15_38_07-250m-1core.srcs/sources_1/imports/f37x-2025-05-08-15_38_07-250m-1core/fpga_all.sv"
#    "/data/disk0/wrk/OpenTF/main/fpga/temp/f37x-2025-05-08-15_38_07-250m-1core/f37x-2025-05-08-15_38_07-250m-1core.srcs/sources_1/imports/f37x-2025-05-08-15_38_07-250m-1core-2022/define.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
   "/home/xlg/wrk/OpenTF/main/fpga/f37x-2024-08-20-09_12_45-1core/f37x-2024-08-20-09_12_45-1core.srcs/sources_1/imports/f37x-2024-08-20-09_12_45-1core/fpga_all.sv" \
   "/home/xlg/wrk/OpenTF/main/fpga/f37x-2024-08-20-09_12_45-1core/f37x-2024-08-20-09_12_45-1core.srcs/constrs_1/imports/f37x-2024-08-20-09_12_45-1core/xilinx_pcie_xdma_ref_board_250MHz.xdc" \
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "f37x"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "f37x_250MHz-2022.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/${_xil_proj_name_}"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcvu37p-fsvh2892-2L-e -force

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "inspur.com:f37x:part0:1.3" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "f37x" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "50" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "48" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "50" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "50" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "50" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "50" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "50" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "1" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/${_xil_proj_name_}/fpga_all.sv" ]\
]
 
 #[file normalize "${origin_dir}/${_xil_proj_name_}/xilinx_ip/ila_0/ila_0.xci" ]\

 #[file normalize "${origin_dir}/${_xil_proj_name_}/xilinx_ip/xilinx_ma/xilinx_ma.xci" ]\
 #[file normalize "${origin_dir}/${_xil_proj_name_}/xilinx_ip/xilinx_fadd/xilinx_fadd.xci" ]\
 #[file normalize "${origin_dir}/${_xil_proj_name_}/xilinx_ip/xilinx_fmult/xilinx_fmult.xci" ]\

set imported_files [import_files -fileset sources_1 $files]

source ${origin_dir}/${_xil_proj_name_}/xilinx_ip/cmac_usplus_0.tcl
source ${origin_dir}/${_xil_proj_name_}/xilinx_ip/cmac_usplus_1.tcl

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "${_xil_proj_name_}/fpga_all.sv"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "design_mode" -value "RTL" -objects $obj
set_property -name "edif_extra_search_paths" -value "" -objects $obj
set_property -name "elab_link_dcps" -value "1" -objects $obj
set_property -name "elab_load_timing_constraints" -value "1" -objects $obj
set_property -name "generic" -value "" -objects $obj
set_property -name "include_dirs" -value "[file normalize "$origin_dir/${_xil_proj_name_}"]" -objects $obj
set_property -name "lib_map_file" -value "" -objects $obj
set_property -name "loop_count" -value "1000" -objects $obj
set_property -name "name" -value "sources_1" -objects $obj
set_property -name "top" -value "f37x_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "verilog_define" -value "" -objects $obj
set_property -name "verilog_uppercase" -value "0" -objects $obj
set_property -name "verilog_version" -value "verilog_2001" -objects $obj
set_property -name "vhdl_version" -value "vhdl_2k" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/${_xil_proj_name_}/xilinx_pcie_xdma_ref_board_250MHz-2022.xdc"]"
set file_imported [import_files -fileset constrs_1 [list $file]]
set file "${_xil_proj_name_}/xilinx_pcie_xdma_ref_board_250MHz-2022.xdc"
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "is_enabled" -value "1" -objects $file_obj
set_property -name "is_global_include" -value "0" -objects $file_obj
set_property -name "library" -value "xil_defaultlib" -objects $file_obj
set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
set_property -name "processing_order" -value "NORMAL" -objects $file_obj
set_property -name "scoped_to_cells" -value "" -objects $file_obj
set_property -name "scoped_to_ref" -value "" -objects $file_obj
set_property -name "used_in" -value "synthesis implementation" -objects $file_obj
set_property -name "used_in_implementation" -value "1" -objects $file_obj
set_property -name "used_in_synthesis" -value "1" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "constrs_type" -value "XDC" -objects $obj
set_property -name "name" -value "constrs_1" -objects $obj
set_property -name "target_constrs_file" -value "" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "32bit" -value "0" -objects $obj
set_property -name "force_compile_glbl" -value "0" -objects $obj
set_property -name "generate_scripts_only" -value "0" -objects $obj
set_property -name "generic" -value "" -objects $obj
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "include_dirs" -value "" -objects $obj
set_property -name "incremental" -value "1" -objects $obj
set_property -name "name" -value "sim_1" -objects $obj
set_property -name "nl.cell" -value "" -objects $obj
set_property -name "nl.incl_unisim_models" -value "0" -objects $obj
set_property -name "nl.process_corner" -value "slow" -objects $obj
set_property -name "nl.rename_top" -value "" -objects $obj
set_property -name "nl.sdf_anno" -value "1" -objects $obj
set_property -name "nl.write_all_overrides" -value "0" -objects $obj
set_property -name "source_set" -value "sources_1" -objects $obj
set_property -name "systemc_include_dirs" -value "" -objects $obj
set_property -name "top" -value "f37x_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "transport_int_delay" -value "0" -objects $obj
set_property -name "transport_path_delay" -value "0" -objects $obj
set_property -name "unifast" -value "0" -objects $obj
set_property -name "verilog_define" -value "" -objects $obj
set_property -name "verilog_uppercase" -value "0" -objects $obj
set_property -name "xelab.dll" -value "0" -objects $obj
set_property -name "xsim.compile.tcl.pre" -value "" -objects $obj
set_property -name "xsim.compile.xsc.more_options" -value "" -objects $obj
set_property -name "xsim.compile.xvhdl.more_options" -value "" -objects $obj
set_property -name "xsim.compile.xvhdl.nosort" -value "1" -objects $obj
set_property -name "xsim.compile.xvhdl.relax" -value "1" -objects $obj
set_property -name "xsim.compile.xvlog.more_options" -value "" -objects $obj
set_property -name "xsim.compile.xvlog.nosort" -value "1" -objects $obj
set_property -name "xsim.compile.xvlog.relax" -value "1" -objects $obj
set_property -name "xsim.elaborate.debug_level" -value "typical" -objects $obj
set_property -name "xsim.elaborate.load_glbl" -value "1" -objects $obj
set_property -name "xsim.elaborate.mt_level" -value "auto" -objects $obj
set_property -name "xsim.elaborate.rangecheck" -value "0" -objects $obj
set_property -name "xsim.elaborate.relax" -value "1" -objects $obj
set_property -name "xsim.elaborate.sdf_delay" -value "sdfmax" -objects $obj
set_property -name "xsim.elaborate.snapshot" -value "" -objects $obj
set_property -name "xsim.elaborate.xelab.more_options" -value "" -objects $obj
set_property -name "xsim.elaborate.xsc.more_options" -value "" -objects $obj
set_property -name "xsim.simulate.add_positional" -value "0" -objects $obj
set_property -name "xsim.simulate.custom_tcl" -value "" -objects $obj
set_property -name "xsim.simulate.log_all_signals" -value "0" -objects $obj
set_property -name "xsim.simulate.no_quit" -value "0" -objects $obj
set_property -name "xsim.simulate.runtime" -value "1000ns" -objects $obj
set_property -name "xsim.simulate.saif" -value "" -objects $obj
set_property -name "xsim.simulate.saif_all_signals" -value "0" -objects $obj
set_property -name "xsim.simulate.saif_scope" -value "" -objects $obj
set_property -name "xsim.simulate.tcl.post" -value "" -objects $obj
set_property -name "xsim.simulate.wdb" -value "" -objects $obj
set_property -name "xsim.simulate.xsim.more_options" -value "" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]
set_property -name "name" -value "utils_1" -objects $obj


# Adding sources referenced in BDs, if not already added


# Proc to create BD pcie_mem
proc cr_bd_pcie_mem { parentCell } {

  # CHANGE DESIGN NAME HERE
  set design_name pcie_mem

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:axi_apb_bridge:3.0\
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:util_ds_buf:2.2\
  xilinx.com:ip:proc_sys_reset:5.0\
  xilinx.com:ip:util_vector_logic:2.0\
  xilinx.com:ip:xdma:4.1\
  xilinx.com:ip:xlconcat:2.1\
  xilinx.com:ip:ddr4:2.2\
  xilinx.com:ip:axi_vip:1.1\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  
# Hierarchical cell: ddr_subsystem
proc create_hier_cell_ddr_subsystem { parentCell nameHier } {

  variable script_folder

  if { $parentCell eq "" || $nameHier eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2092 -severity "ERROR" "create_hier_cell_ddr_subsystem() - Empty argument(s)!"}
     return
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj

  # Create cell and set as current instance
  set hier_obj [create_bd_cell -type hier $nameHier]
  current_bd_instance $hier_obj

  # Create interface pins
  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 AI_S01_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 AI_S02_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 AI_S03_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 AI_S04_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 AI_S05_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 AI_S06_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 AI_S07_AXI

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 DDR4_C0_SYS_CLK

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 DDR4_C1_SYS_CLK

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 DDR4_C2_SYS_CLK

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 DDR4_MEM_C0

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 DDR4_MEM_C1

  create_bd_intf_pin -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 DDR4_MEM_C2

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 DDR4_MEM_CTRL_S00_AXI_0

  create_bd_intf_pin -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 DDR4_MEM_S00_AXI


  # Create pins
  create_bd_pin -dir I -type clk DDR4_MEM_CTRL_S00_ACLK_0
  create_bd_pin -dir I -type rst DDR4_MEM_CTRL_S00_ARESETN_0
  create_bd_pin -dir I -type clk DDR4_MEM_S00_ACLK
  create_bd_pin -dir I -type rst DDR4_MEM_S00_ARESETN
  create_bd_pin -dir I -type clk S01_ACLK_0
  create_bd_pin -dir I -type rst S01_ARESETN_0
  create_bd_pin -dir I -type clk S02_ACLK_0
  create_bd_pin -dir I -type rst S02_ARESETN_0
  create_bd_pin -dir I -type clk S03_ACLK_0
  create_bd_pin -dir I -type rst S03_ARESETN_0
  create_bd_pin -dir I -type clk S04_ACLK_0
  create_bd_pin -dir I -type rst S04_ARESETN_0
  create_bd_pin -dir I -type clk S05_ACLK_0
  create_bd_pin -dir I -type rst S05_ARESETN_0
  create_bd_pin -dir I -type clk S06_ACLK_0
  create_bd_pin -dir I -type rst S06_ARESETN_0
  create_bd_pin -dir I -type clk S07_ACLK_0
  create_bd_pin -dir I -type rst S07_ARESETN_0
  create_bd_pin -dir O -from 0 -to 0 -type rst ddr4_c0_aresetn
  create_bd_pin -dir O -type clk ddr4_c0_ui_clk
  create_bd_pin -dir O -from 0 -to 0 -type rst ddr4_c1_aresetn
  create_bd_pin -dir O -type clk ddr4_c1_ui_clk
  create_bd_pin -dir O -from 0 -to 0 -type rst ddr4_c2_aresetn
  create_bd_pin -dir O -type clk ddr4_c2_ui_clk
  create_bd_pin -dir O ddr4_init_calib_complete_c0
  create_bd_pin -dir O ddr4_init_calib_complete_c1
  create_bd_pin -dir O ddr4_init_calib_complete_c2
  create_bd_pin -dir I -type rst ddr4_sys_rst_c0
  create_bd_pin -dir I -type rst ddr4_sys_rst_c1
  create_bd_pin -dir I -type rst ddr4_sys_rst_c2

  ### Create instance: axi_interconnect_3in1, and set properties
  ##set axi_interconnect_3in1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_3in1 ]
  ##set_property -dict [list \
  ##  CONFIG.M00_HAS_REGSLICE {3} \
  ##  CONFIG.M01_HAS_REGSLICE {3} \
  ##  CONFIG.M02_HAS_REGSLICE {3} \
  ##  CONFIG.NUM_MI {3} \
  ##  CONFIG.NUM_SI {8} \
  ##  CONFIG.S00_HAS_REGSLICE {3} \
  ##  CONFIG.S01_HAS_REGSLICE {3} \
  ##  CONFIG.S02_HAS_REGSLICE {3} \
  ##  CONFIG.S03_HAS_REGSLICE {3} \
  ##  CONFIG.S04_HAS_REGSLICE {3} \
  ##  CONFIG.S05_HAS_REGSLICE {3} \
  ##  CONFIG.S06_HAS_REGSLICE {3} \
  ##  CONFIG.S07_HAS_REGSLICE {3} \
  ##] $axi_interconnect_3in1

  # Create instance: axi_interconnect_3in1, and set properties
  set axi_interconnect_3in1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_3in1 ]
  set_property -dict [list \
    CONFIG.M00_HAS_REGSLICE {3} \
    CONFIG.M01_HAS_REGSLICE {3} \
    CONFIG.M02_HAS_REGSLICE {3} \
    CONFIG.NUM_MI {3} \
    CONFIG.NUM_SI {8} \
    CONFIG.S00_HAS_DATA_FIFO {2} \
    CONFIG.S00_HAS_REGSLICE {3} \
    CONFIG.S01_HAS_DATA_FIFO {2} \
    CONFIG.S01_HAS_REGSLICE {3} \
    CONFIG.S02_HAS_DATA_FIFO {2} \
    CONFIG.S02_HAS_REGSLICE {3} \
    CONFIG.S03_HAS_DATA_FIFO {2} \
    CONFIG.S03_HAS_REGSLICE {3} \
    CONFIG.S04_HAS_DATA_FIFO {2} \
    CONFIG.S04_HAS_REGSLICE {3} \
    CONFIG.S05_HAS_DATA_FIFO {2} \
    CONFIG.S05_HAS_REGSLICE {3} \
    CONFIG.S06_HAS_DATA_FIFO {2} \
    CONFIG.S06_HAS_REGSLICE {3} \
    CONFIG.S07_HAS_DATA_FIFO {2} \
    CONFIG.S07_HAS_REGSLICE {3} \
    CONFIG.STRATEGY {2} \
  ] $axi_interconnect_3in1


  # Create instance: axi_interconnect_ctrl_0, and set properties
  set axi_interconnect_ctrl_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_ctrl_0 ]
  set_property -dict [list \
    CONFIG.M00_HAS_REGSLICE {3} \
    CONFIG.M01_HAS_REGSLICE {3} \
    CONFIG.M02_HAS_REGSLICE {3} \
    CONFIG.NUM_MI {3} \
    CONFIG.S00_HAS_REGSLICE {3} \
  ] $axi_interconnect_ctrl_0


  # Create instance: ddr4_mem_c0, and set properties
  set ddr4_mem_c0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ddr4:2.2 ddr4_mem_c0 ]
  set_property -dict [list \
    CONFIG.ADDN_UI_CLKOUT1_FREQ_HZ {100} \
    CONFIG.C0.DDR4_AxiAddressWidth {33} \
    CONFIG.C0.DDR4_DataMask {NO_DM_NO_DBI} \
    CONFIG.C0_CLOCK_BOARD_INTERFACE {default_300mhz_clk0} \
    CONFIG.C0_DDR4_BOARD_INTERFACE {ddr4_sdram_c0} \
  ] $ddr4_mem_c0


  # Create instance: ddr4_mem_c1, and set properties
  set ddr4_mem_c1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ddr4:2.2 ddr4_mem_c1 ]
  set_property -dict [list \
    CONFIG.ADDN_UI_CLKOUT1_FREQ_HZ {100} \
    CONFIG.C0.DDR4_AxiAddressWidth {33} \
    CONFIG.C0.DDR4_DataMask {NO_DM_NO_DBI} \
    CONFIG.C0_CLOCK_BOARD_INTERFACE {default_300mhz_clk1} \
    CONFIG.C0_DDR4_BOARD_INTERFACE {ddr4_sdram_c1} \
  ] $ddr4_mem_c1


  # Create instance: ddr4_mem_c2, and set properties
  set ddr4_mem_c2 [ create_bd_cell -type ip -vlnv xilinx.com:ip:ddr4:2.2 ddr4_mem_c2 ]
  set_property -dict [list \
    CONFIG.ADDN_UI_CLKOUT1_FREQ_HZ {100} \
    CONFIG.C0.DDR4_AxiAddressWidth {33} \
    CONFIG.C0.DDR4_DataMask {NO_DM_NO_DBI} \
    CONFIG.C0_CLOCK_BOARD_INTERFACE {default_300mhz_clk2} \
    CONFIG.C0_DDR4_BOARD_INTERFACE {ddr4_sdram_c2} \
  ] $ddr4_mem_c2


  # Create instance: proc_sys_reset_c0, and set properties
  set proc_sys_reset_c0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 proc_sys_reset_c0 ]

  # Create instance: proc_sys_reset_c1, and set properties
  set proc_sys_reset_c1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 proc_sys_reset_c1 ]

  # Create instance: proc_sys_reset_c2, and set properties
  set proc_sys_reset_c2 [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 proc_sys_reset_c2 ]

  # Create instance: vip_ddr4_mem_c0, and set properties
  set vip_ddr4_mem_c0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vip:1.1 vip_ddr4_mem_c0 ]

  # Create instance: vip_ddr4_mem_c1, and set properties
  set vip_ddr4_mem_c1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vip:1.1 vip_ddr4_mem_c1 ]

  # Create instance: vip_ddr4_mem_c2, and set properties
  set vip_ddr4_mem_c2 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vip:1.1 vip_ddr4_mem_c2 ]

  # Create instance: vip_mem_ctrl_c0, and set properties
  set vip_mem_ctrl_c0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vip:1.1 vip_mem_ctrl_c0 ]

  # Create instance: vip_mem_ctrl_c1, and set properties
  set vip_mem_ctrl_c1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vip:1.1 vip_mem_ctrl_c1 ]

  # Create instance: vip_mem_ctrl_c2, and set properties
  set vip_mem_ctrl_c2 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_vip:1.1 vip_mem_ctrl_c2 ]

  # Create interface connections
  connect_bd_intf_net -intf_net Conn1 [get_bd_intf_pins DDR4_C0_SYS_CLK] [get_bd_intf_pins ddr4_mem_c0/C0_SYS_CLK]
  connect_bd_intf_net -intf_net Conn2 [get_bd_intf_pins DDR4_MEM_C0] [get_bd_intf_pins ddr4_mem_c0/C0_DDR4]
  connect_bd_intf_net -intf_net Conn3 [get_bd_intf_pins DDR4_MEM_CTRL_S00_AXI_0] [get_bd_intf_pins axi_interconnect_ctrl_0/S00_AXI]
  connect_bd_intf_net -intf_net Conn4 [get_bd_intf_pins DDR4_C1_SYS_CLK] [get_bd_intf_pins ddr4_mem_c1/C0_SYS_CLK]
  connect_bd_intf_net -intf_net Conn5 [get_bd_intf_pins DDR4_MEM_C1] [get_bd_intf_pins ddr4_mem_c1/C0_DDR4]
  connect_bd_intf_net -intf_net Conn6 [get_bd_intf_pins DDR4_C2_SYS_CLK] [get_bd_intf_pins ddr4_mem_c2/C0_SYS_CLK]
  connect_bd_intf_net -intf_net Conn7 [get_bd_intf_pins DDR4_MEM_C2] [get_bd_intf_pins ddr4_mem_c2/C0_DDR4]
  connect_bd_intf_net -intf_net Conn8 [get_bd_intf_pins DDR4_MEM_S00_AXI] [get_bd_intf_pins axi_interconnect_3in1/S00_AXI]
  connect_bd_intf_net -intf_net Conn9 [get_bd_intf_pins AI_S01_AXI] [get_bd_intf_pins axi_interconnect_3in1/S01_AXI]
  connect_bd_intf_net -intf_net Conn10 [get_bd_intf_pins AI_S02_AXI] [get_bd_intf_pins axi_interconnect_3in1/S02_AXI]
  connect_bd_intf_net -intf_net Conn11 [get_bd_intf_pins AI_S03_AXI] [get_bd_intf_pins axi_interconnect_3in1/S03_AXI]
  connect_bd_intf_net -intf_net Conn12 [get_bd_intf_pins AI_S04_AXI] [get_bd_intf_pins axi_interconnect_3in1/S04_AXI]
  connect_bd_intf_net -intf_net Conn13 [get_bd_intf_pins AI_S05_AXI] [get_bd_intf_pins axi_interconnect_3in1/S05_AXI]
  connect_bd_intf_net -intf_net Conn14 [get_bd_intf_pins AI_S06_AXI] [get_bd_intf_pins axi_interconnect_3in1/S06_AXI]
  connect_bd_intf_net -intf_net Conn15 [get_bd_intf_pins AI_S07_AXI] [get_bd_intf_pins axi_interconnect_3in1/S07_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_3in1_M00_AXI [get_bd_intf_pins axi_interconnect_3in1/M00_AXI] [get_bd_intf_pins vip_ddr4_mem_c0/S_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_3in1_M01_AXI [get_bd_intf_pins axi_interconnect_3in1/M01_AXI] [get_bd_intf_pins vip_ddr4_mem_c1/S_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_3in1_M02_AXI [get_bd_intf_pins axi_interconnect_3in1/M02_AXI] [get_bd_intf_pins vip_ddr4_mem_c2/S_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_ctrl_0_M00_AXI [get_bd_intf_pins axi_interconnect_ctrl_0/M00_AXI] [get_bd_intf_pins vip_mem_ctrl_c0/S_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_ctrl_0_M01_AXI [get_bd_intf_pins axi_interconnect_ctrl_0/M01_AXI] [get_bd_intf_pins vip_mem_ctrl_c1/S_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_ctrl_0_M02_AXI [get_bd_intf_pins axi_interconnect_ctrl_0/M02_AXI] [get_bd_intf_pins vip_mem_ctrl_c2/S_AXI]
  connect_bd_intf_net -intf_net vip_ddr4_mem_c0_M_AXI [get_bd_intf_pins ddr4_mem_c0/C0_DDR4_S_AXI] [get_bd_intf_pins vip_ddr4_mem_c0/M_AXI]
  connect_bd_intf_net -intf_net vip_ddr4_mem_c1_M_AXI [get_bd_intf_pins ddr4_mem_c1/C0_DDR4_S_AXI] [get_bd_intf_pins vip_ddr4_mem_c1/M_AXI]
  connect_bd_intf_net -intf_net vip_ddr4_mem_c2_M_AXI [get_bd_intf_pins ddr4_mem_c2/C0_DDR4_S_AXI] [get_bd_intf_pins vip_ddr4_mem_c2/M_AXI]
  connect_bd_intf_net -intf_net vip_mem_ctrl_c0_M_AXI [get_bd_intf_pins ddr4_mem_c0/C0_DDR4_S_AXI_CTRL] [get_bd_intf_pins vip_mem_ctrl_c0/M_AXI]
  connect_bd_intf_net -intf_net vip_mem_ctrl_c1_M_AXI [get_bd_intf_pins ddr4_mem_c1/C0_DDR4_S_AXI_CTRL] [get_bd_intf_pins vip_mem_ctrl_c1/M_AXI]
  connect_bd_intf_net -intf_net vip_mem_ctrl_c2_M_AXI [get_bd_intf_pins ddr4_mem_c2/C0_DDR4_S_AXI_CTRL] [get_bd_intf_pins vip_mem_ctrl_c2/M_AXI]

  # Create port connections
  connect_bd_net -net S00_ACLK_1 [get_bd_pins DDR4_MEM_CTRL_S00_ACLK_0] [get_bd_pins axi_interconnect_ctrl_0/ACLK] [get_bd_pins axi_interconnect_ctrl_0/S00_ACLK]
  connect_bd_net -net S00_ACLK_3 [get_bd_pins DDR4_MEM_S00_ACLK] [get_bd_pins axi_interconnect_3in1/ACLK] [get_bd_pins axi_interconnect_3in1/S00_ACLK]
  connect_bd_net -net S00_ARESETN_1 [get_bd_pins DDR4_MEM_CTRL_S00_ARESETN_0] [get_bd_pins axi_interconnect_ctrl_0/ARESETN] [get_bd_pins axi_interconnect_ctrl_0/S00_ARESETN]
  connect_bd_net -net S00_ARESETN_3 [get_bd_pins DDR4_MEM_S00_ARESETN] [get_bd_pins axi_interconnect_3in1/ARESETN] [get_bd_pins axi_interconnect_3in1/S00_ARESETN]
  connect_bd_net -net S01_ACLK_1 [get_bd_pins S01_ACLK_0] [get_bd_pins axi_interconnect_3in1/S01_ACLK]
  connect_bd_net -net S01_ARESETN_1 [get_bd_pins S01_ARESETN_0] [get_bd_pins axi_interconnect_3in1/S01_ARESETN]
  connect_bd_net -net S02_ACLK_1 [get_bd_pins S02_ACLK_0] [get_bd_pins axi_interconnect_3in1/S02_ACLK]
  connect_bd_net -net S02_ARESETN_1 [get_bd_pins S02_ARESETN_0] [get_bd_pins axi_interconnect_3in1/S02_ARESETN]
  connect_bd_net -net S03_ACLK_1 [get_bd_pins S03_ACLK_0] [get_bd_pins axi_interconnect_3in1/S03_ACLK]
  connect_bd_net -net S03_ARESETN_1 [get_bd_pins S03_ARESETN_0] [get_bd_pins axi_interconnect_3in1/S03_ARESETN]
  connect_bd_net -net S04_ACLK_1 [get_bd_pins S04_ACLK_0] [get_bd_pins axi_interconnect_3in1/S04_ACLK]
  connect_bd_net -net S04_ARESETN_1 [get_bd_pins S04_ARESETN_0] [get_bd_pins axi_interconnect_3in1/S04_ARESETN]
  connect_bd_net -net S05_ACLK_1 [get_bd_pins S05_ACLK_0] [get_bd_pins axi_interconnect_3in1/S05_ACLK]
  connect_bd_net -net S05_ARESETN_1 [get_bd_pins S05_ARESETN_0] [get_bd_pins axi_interconnect_3in1/S05_ARESETN]
  connect_bd_net -net S06_ACLK_1 [get_bd_pins S06_ACLK_0] [get_bd_pins axi_interconnect_3in1/S06_ACLK]
  connect_bd_net -net S06_ARESETN_1 [get_bd_pins S06_ARESETN_0] [get_bd_pins axi_interconnect_3in1/S06_ARESETN]
  connect_bd_net -net S07_ACLK_1 [get_bd_pins S07_ACLK_0] [get_bd_pins axi_interconnect_3in1/S07_ACLK]
  connect_bd_net -net S07_ARESETN_1 [get_bd_pins S07_ARESETN_0] [get_bd_pins axi_interconnect_3in1/S07_ARESETN]
  connect_bd_net -net ddr4_mem_c0_c0_ddr4_ui_clk [get_bd_pins ddr4_c0_ui_clk] [get_bd_pins axi_interconnect_3in1/M00_ACLK] [get_bd_pins axi_interconnect_ctrl_0/M00_ACLK] [get_bd_pins ddr4_mem_c0/c0_ddr4_ui_clk] [get_bd_pins proc_sys_reset_c0/slowest_sync_clk] [get_bd_pins vip_ddr4_mem_c0/aclk] [get_bd_pins vip_mem_ctrl_c0/aclk]
  connect_bd_net -net ddr4_mem_c0_c0_ddr4_ui_clk_sync_rst [get_bd_pins ddr4_mem_c0/c0_ddr4_ui_clk_sync_rst] [get_bd_pins proc_sys_reset_c0/ext_reset_in]
  connect_bd_net -net ddr4_mem_c0_c0_init_calib_complete [get_bd_pins ddr4_init_calib_complete_c0] [get_bd_pins ddr4_mem_c0/c0_init_calib_complete]
  connect_bd_net -net ddr4_mem_c1_c0_ddr4_ui_clk [get_bd_pins ddr4_c1_ui_clk] [get_bd_pins axi_interconnect_3in1/M01_ACLK] [get_bd_pins axi_interconnect_ctrl_0/M01_ACLK] [get_bd_pins ddr4_mem_c1/c0_ddr4_ui_clk] [get_bd_pins proc_sys_reset_c1/slowest_sync_clk] [get_bd_pins vip_ddr4_mem_c1/aclk] [get_bd_pins vip_mem_ctrl_c1/aclk]
  connect_bd_net -net ddr4_mem_c1_c0_ddr4_ui_clk_sync_rst [get_bd_pins ddr4_mem_c1/c0_ddr4_ui_clk_sync_rst] [get_bd_pins proc_sys_reset_c1/ext_reset_in]
  connect_bd_net -net ddr4_mem_c1_c0_init_calib_complete [get_bd_pins ddr4_init_calib_complete_c1] [get_bd_pins ddr4_mem_c1/c0_init_calib_complete]
  connect_bd_net -net ddr4_mem_c2_c0_ddr4_ui_clk [get_bd_pins ddr4_c2_ui_clk] [get_bd_pins axi_interconnect_3in1/M02_ACLK] [get_bd_pins axi_interconnect_ctrl_0/M02_ACLK] [get_bd_pins ddr4_mem_c2/c0_ddr4_ui_clk] [get_bd_pins proc_sys_reset_c2/slowest_sync_clk] [get_bd_pins vip_ddr4_mem_c2/aclk] [get_bd_pins vip_mem_ctrl_c2/aclk]
  connect_bd_net -net ddr4_mem_c2_c0_ddr4_ui_clk_sync_rst [get_bd_pins ddr4_mem_c2/c0_ddr4_ui_clk_sync_rst] [get_bd_pins proc_sys_reset_c2/ext_reset_in]
  connect_bd_net -net ddr4_mem_c2_c0_init_calib_complete [get_bd_pins ddr4_init_calib_complete_c2] [get_bd_pins ddr4_mem_c2/c0_init_calib_complete]
  connect_bd_net -net proc_sys_reset_0_interconnect_aresetn [get_bd_pins ddr4_c0_aresetn] [get_bd_pins axi_interconnect_3in1/M00_ARESETN] [get_bd_pins axi_interconnect_ctrl_0/M00_ARESETN] [get_bd_pins ddr4_mem_c0/c0_ddr4_aresetn] [get_bd_pins proc_sys_reset_c0/interconnect_aresetn] [get_bd_pins vip_ddr4_mem_c0/aresetn] [get_bd_pins vip_mem_ctrl_c0/aresetn]
  connect_bd_net -net proc_sys_reset_c1_interconnect_aresetn [get_bd_pins ddr4_c1_aresetn] [get_bd_pins axi_interconnect_3in1/M01_ARESETN] [get_bd_pins axi_interconnect_ctrl_0/M01_ARESETN] [get_bd_pins ddr4_mem_c1/c0_ddr4_aresetn] [get_bd_pins proc_sys_reset_c1/interconnect_aresetn] [get_bd_pins vip_ddr4_mem_c1/aresetn] [get_bd_pins vip_mem_ctrl_c1/aresetn]
  connect_bd_net -net proc_sys_reset_c2_interconnect_aresetn [get_bd_pins ddr4_c2_aresetn] [get_bd_pins axi_interconnect_3in1/M02_ARESETN] [get_bd_pins axi_interconnect_ctrl_0/M02_ARESETN] [get_bd_pins ddr4_mem_c2/c0_ddr4_aresetn] [get_bd_pins proc_sys_reset_c2/interconnect_aresetn] [get_bd_pins vip_ddr4_mem_c2/aresetn] [get_bd_pins vip_mem_ctrl_c2/aresetn]
  connect_bd_net -net sys_rst_0_1 [get_bd_pins ddr4_sys_rst_c0] [get_bd_pins ddr4_mem_c0/sys_rst]
  connect_bd_net -net sys_rst_1_1 [get_bd_pins ddr4_sys_rst_c1] [get_bd_pins ddr4_mem_c1/sys_rst]
  connect_bd_net -net sys_rst_2_1 [get_bd_pins ddr4_sys_rst_c2] [get_bd_pins ddr4_mem_c2/sys_rst]

  # Restore current instance
  current_bd_instance $oldCurInst
}
  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set S01_AXI_1 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S01_AXI_1 ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {64} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {512} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {1} \
   CONFIG.HAS_CACHE {1} \
   CONFIG.HAS_LOCK {1} \
   CONFIG.HAS_PROT {1} \
   CONFIG.HAS_QOS {1} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {1} \
   CONFIG.ID_WIDTH {7} \
   CONFIG.MAX_BURST_LENGTH {256} \
   CONFIG.NUM_READ_OUTSTANDING {2} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {2} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.SUPPORTS_NARROW_BURST {1} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $S01_AXI_1

  set S02_AXI_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S02_AXI_0 ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {64} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {512} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {1} \
   CONFIG.HAS_CACHE {1} \
   CONFIG.HAS_LOCK {1} \
   CONFIG.HAS_PROT {1} \
   CONFIG.HAS_QOS {1} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {1} \
   CONFIG.ID_WIDTH {7} \
   CONFIG.MAX_BURST_LENGTH {256} \
   CONFIG.NUM_READ_OUTSTANDING {2} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {2} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.SUPPORTS_NARROW_BURST {1} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $S02_AXI_0

  set S03_AXI_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S03_AXI_0 ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {64} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {512} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {1} \
   CONFIG.HAS_CACHE {1} \
   CONFIG.HAS_LOCK {1} \
   CONFIG.HAS_PROT {1} \
   CONFIG.HAS_QOS {1} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {1} \
   CONFIG.ID_WIDTH {7} \
   CONFIG.MAX_BURST_LENGTH {256} \
   CONFIG.NUM_READ_OUTSTANDING {2} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {2} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.SUPPORTS_NARROW_BURST {1} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $S03_AXI_0

  set S04_AXI_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S04_AXI_0 ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {64} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {512} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {1} \
   CONFIG.HAS_CACHE {1} \
   CONFIG.HAS_LOCK {1} \
   CONFIG.HAS_PROT {1} \
   CONFIG.HAS_QOS {1} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {1} \
   CONFIG.ID_WIDTH {7} \
   CONFIG.MAX_BURST_LENGTH {256} \
   CONFIG.NUM_READ_OUTSTANDING {2} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {2} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.SUPPORTS_NARROW_BURST {1} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $S04_AXI_0

  set S05_AXI_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S05_AXI_0 ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {64} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {512} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {1} \
   CONFIG.HAS_CACHE {1} \
   CONFIG.HAS_LOCK {1} \
   CONFIG.HAS_PROT {1} \
   CONFIG.HAS_QOS {1} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {1} \
   CONFIG.ID_WIDTH {7} \
   CONFIG.MAX_BURST_LENGTH {256} \
   CONFIG.NUM_READ_OUTSTANDING {2} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {2} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.SUPPORTS_NARROW_BURST {1} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $S05_AXI_0

  set S06_AXI_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S06_AXI_0 ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {64} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {512} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {1} \
   CONFIG.HAS_CACHE {1} \
   CONFIG.HAS_LOCK {1} \
   CONFIG.HAS_PROT {1} \
   CONFIG.HAS_QOS {1} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {1} \
   CONFIG.ID_WIDTH {7} \
   CONFIG.MAX_BURST_LENGTH {256} \
   CONFIG.NUM_READ_OUTSTANDING {2} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {2} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.SUPPORTS_NARROW_BURST {1} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $S06_AXI_0

  set S07_AXI_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:aximm_rtl:1.0 S07_AXI_0 ]
  set_property -dict [ list \
   CONFIG.ADDR_WIDTH {64} \
   CONFIG.ARUSER_WIDTH {0} \
   CONFIG.AWUSER_WIDTH {0} \
   CONFIG.BUSER_WIDTH {0} \
   CONFIG.DATA_WIDTH {512} \
   CONFIG.HAS_BRESP {1} \
   CONFIG.HAS_BURST {1} \
   CONFIG.HAS_CACHE {1} \
   CONFIG.HAS_LOCK {1} \
   CONFIG.HAS_PROT {1} \
   CONFIG.HAS_QOS {1} \
   CONFIG.HAS_REGION {0} \
   CONFIG.HAS_RRESP {1} \
   CONFIG.HAS_WSTRB {1} \
   CONFIG.ID_WIDTH {7} \
   CONFIG.MAX_BURST_LENGTH {256} \
   CONFIG.NUM_READ_OUTSTANDING {2} \
   CONFIG.NUM_READ_THREADS {1} \
   CONFIG.NUM_WRITE_OUTSTANDING {2} \
   CONFIG.NUM_WRITE_THREADS {1} \
   CONFIG.PROTOCOL {AXI4} \
   CONFIG.READ_WRITE_MODE {READ_WRITE} \
   CONFIG.RUSER_BITS_PER_BYTE {0} \
   CONFIG.RUSER_WIDTH {0} \
   CONFIG.SUPPORTS_NARROW_BURST {1} \
   CONFIG.WUSER_BITS_PER_BYTE {0} \
   CONFIG.WUSER_WIDTH {0} \
   ] $S07_AXI_0

  set ai_cfg_apb_m [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:apb_rtl:1.0 ai_cfg_apb_m ]

  set c0_ddr4 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 c0_ddr4 ]

  set c0_sys [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 c0_sys ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {300120000} \
   ] $c0_sys

  set c1_ddr4 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 c1_ddr4 ]

  set c1_sys [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 c1_sys ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {300120000} \
   ] $c1_sys

  set c2_ddr4 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddr4_rtl:1.0 c2_ddr4 ]

  set c2_sys [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 c2_sys ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {300120000} \
   ] $c2_sys

  set pci_exp [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:pcie_7x_mgt_rtl:1.0 pci_exp ]

  set sys [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 sys ]


  # Create ports
  set ai_clk_100mhz [ create_bd_port -dir O -type clk ai_clk_100mhz ]
  set_property -dict [ list \
   CONFIG.ASSOCIATED_BUSIF {S01_AXI_1:S02_AXI_0:S03_AXI_0:S04_AXI_0:S05_AXI_0:S06_AXI_0:S07_AXI_0} \
 ] $ai_clk_100mhz
  set ai_rst [ create_bd_port -dir O -from 0 -to 0 ai_rst ]
  set dout_0 [ create_bd_port -dir O -from 2 -to 0 dout_0 ]
  set sys_rst_n [ create_bd_port -dir I -type rst sys_rst_n ]
  set_property -dict [ list \
   CONFIG.POLARITY {ACTIVE_LOW} \
 ] $sys_rst_n
  set usr_irq_req_0 [ create_bd_port -dir I -from 15 -to 0 usr_irq_req_0 ]

  # Create instance: axi_apb_bridge_1, and set properties
  set axi_apb_bridge_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_apb_bridge:3.0 axi_apb_bridge_1 ]
  set_property CONFIG.C_APB_NUM_SLAVES {1} $axi_apb_bridge_1


  # Create instance: axi_interconnect_0, and set properties
  set axi_interconnect_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_0 ]
  set_property -dict [list \
    CONFIG.M00_HAS_REGSLICE {3} \
    CONFIG.M01_HAS_REGSLICE {3} \
    CONFIG.M02_HAS_REGSLICE {3} \
    CONFIG.NUM_MI {2} \
    CONFIG.NUM_SI {1} \
    CONFIG.S00_HAS_REGSLICE {3} \
  ] $axi_interconnect_0


  # Create instance: axi_interconnect_1, and set properties
  set axi_interconnect_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_interconnect:2.1 axi_interconnect_1 ]
  set_property -dict [list \
    CONFIG.M00_HAS_REGSLICE {3} \
    CONFIG.M01_HAS_REGSLICE {3} \
    CONFIG.NUM_MI {1} \
    CONFIG.NUM_SI {1} \
    CONFIG.S00_HAS_REGSLICE {3} \
  ] $axi_interconnect_1


  # Create instance: ddr_subsystem
  create_hier_cell_ddr_subsystem [current_bd_instance .] ddr_subsystem

  # Create instance: hbm_100m_clk_mmcm, and set properties
  set hbm_100m_clk_mmcm [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 hbm_100m_clk_mmcm ]
  set_property -dict [list \
    CONFIG.CLKIN1_JITTER_PS {40.0} \
    CONFIG.CLKOUT1_DRIVES {Buffer} \
    CONFIG.CLKOUT1_JITTER {134.506} \
    CONFIG.CLKOUT1_PHASE_ERROR {154.678} \
    CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {100.000} \
    CONFIG.CLKOUT2_DRIVES {Buffer} \
    CONFIG.CLKOUT3_DRIVES {Buffer} \
    CONFIG.CLKOUT4_DRIVES {Buffer} \
    CONFIG.CLKOUT5_DRIVES {Buffer} \
    CONFIG.CLKOUT6_DRIVES {Buffer} \
    CONFIG.CLKOUT7_DRIVES {Buffer} \
    CONFIG.FEEDBACK_SOURCE {FDBK_AUTO} \
    CONFIG.MMCM_BANDWIDTH {OPTIMIZED} \
    CONFIG.MMCM_CLKFBOUT_MULT_F {24.000} \
    CONFIG.MMCM_CLKIN1_PERIOD {4.000} \
    CONFIG.MMCM_CLKIN2_PERIOD {10.0} \
    CONFIG.MMCM_CLKOUT0_DIVIDE_F {12.000} \
    CONFIG.MMCM_COMPENSATION {AUTO} \
    CONFIG.MMCM_DIVCLK_DIVIDE {5} \
    CONFIG.PLL_CLKIN_PERIOD {4.000} \
    CONFIG.PRIMITIVE {MMCM} \
    CONFIG.PRIM_IN_FREQ {250.000} \
    CONFIG.RESET_PORT {resetn} \
    CONFIG.RESET_TYPE {ACTIVE_LOW} \
  ] $hbm_100m_clk_mmcm


  # Create instance: pcie_ref_clk_buffer, and set properties
  set pcie_ref_clk_buffer [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_ds_buf:2.2 pcie_ref_clk_buffer ]
  set_property CONFIG.C_BUF_TYPE {IBUFDSGTE} $pcie_ref_clk_buffer


  # Create instance: proc_sys_reset_0, and set properties
  set proc_sys_reset_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 proc_sys_reset_0 ]

  # Create instance: util_vector_logic_0, and set properties
  set util_vector_logic_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 util_vector_logic_0 ]
  set_property -dict [list \
    CONFIG.C_OPERATION {not} \
    CONFIG.C_SIZE {1} \
  ] $util_vector_logic_0


  # Create instance: util_vector_logic_1, and set properties
  set util_vector_logic_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:util_vector_logic:2.0 util_vector_logic_1 ]
  set_property -dict [list \
    CONFIG.C_OPERATION {not} \
    CONFIG.C_SIZE {1} \
  ] $util_vector_logic_1


  # Create instance: xdma_0, and set properties
  set xdma_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xdma:4.1 xdma_0 ]
  set_property -dict [list \
    CONFIG.PF0_DEVICE_ID_mqdma {903F} \
    CONFIG.PF0_SRIOV_VF_DEVICE_ID {0000} \
    CONFIG.PF2_DEVICE_ID_mqdma {903F} \
    CONFIG.PF3_DEVICE_ID_mqdma {903F} \
    CONFIG.axi_data_width {512_bit} \
    CONFIG.axilite_master_en {true} \
    CONFIG.axilite_master_size {8} \
    CONFIG.axist_bypass_en {false} \
    CONFIG.axisten_freq {250} \
    CONFIG.cfg_mgmt_if {false} \
    CONFIG.copy_pf0 {true} \
    CONFIG.mode_selection {Advanced} \
    CONFIG.pcie_blk_locn {PCIE4C_X1Y0} \
    CONFIG.pf0_device_id {903F} \
    CONFIG.pf0_interrupt_pin {NONE} \
    CONFIG.pf0_msi_enabled {false} \
    CONFIG.pf0_msix_cap_pba_bir {BAR_1} \
    CONFIG.pf0_msix_cap_pba_offset {00008FE0} \
    CONFIG.pf0_msix_cap_table_bir {BAR_1} \
    CONFIG.pf0_msix_cap_table_offset {00008000} \
    CONFIG.pf0_msix_cap_table_size {01F} \
    CONFIG.pf0_msix_enabled {true} \
    CONFIG.pl_link_cap_max_link_speed {8.0_GT/s} \
    CONFIG.pl_link_cap_max_link_width {X16} \
    CONFIG.plltype {QPLL1} \
    CONFIG.runbit_fix {false} \
    CONFIG.xdma_num_usr_irq {16} \
    CONFIG.xlnx_ref_board {F37X} \
  ] $xdma_0


  # Create instance: xlconcat_0, and set properties
  set xlconcat_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:xlconcat:2.1 xlconcat_0 ]
  set_property CONFIG.NUM_PORTS {3} $xlconcat_0


  # Create interface connections
  connect_bd_intf_net -intf_net CLK_IN_D_0_1 [get_bd_intf_ports sys] [get_bd_intf_pins pcie_ref_clk_buffer/CLK_IN_D]
  connect_bd_intf_net -intf_net DDR4_C0_SYS_CLK_0_1 [get_bd_intf_ports c0_sys] [get_bd_intf_pins ddr_subsystem/DDR4_C0_SYS_CLK]
  connect_bd_intf_net -intf_net DDR4_C1_SYS_CLK_0_1 [get_bd_intf_ports c1_sys] [get_bd_intf_pins ddr_subsystem/DDR4_C1_SYS_CLK]
  connect_bd_intf_net -intf_net DDR4_C2_SYS_CLK_0_1 [get_bd_intf_ports c2_sys] [get_bd_intf_pins ddr_subsystem/DDR4_C2_SYS_CLK]
  connect_bd_intf_net -intf_net S00_AXI_1 [get_bd_intf_pins axi_interconnect_0/S00_AXI] [get_bd_intf_pins xdma_0/M_AXI_LITE]
  connect_bd_intf_net -intf_net S01_AXI_1_1 [get_bd_intf_ports S01_AXI_1] [get_bd_intf_pins ddr_subsystem/AI_S01_AXI]
  connect_bd_intf_net -intf_net S02_AXI_0_1 [get_bd_intf_ports S02_AXI_0] [get_bd_intf_pins ddr_subsystem/AI_S02_AXI]
  connect_bd_intf_net -intf_net S03_AXI_0_1 [get_bd_intf_ports S03_AXI_0] [get_bd_intf_pins ddr_subsystem/AI_S03_AXI]
  connect_bd_intf_net -intf_net S04_AXI_0_1 [get_bd_intf_ports S04_AXI_0] [get_bd_intf_pins ddr_subsystem/AI_S04_AXI]
  connect_bd_intf_net -intf_net S05_AXI_0_1 [get_bd_intf_ports S05_AXI_0] [get_bd_intf_pins ddr_subsystem/AI_S05_AXI]
  connect_bd_intf_net -intf_net S06_AXI_0_1 [get_bd_intf_ports S06_AXI_0] [get_bd_intf_pins ddr_subsystem/AI_S06_AXI]
  connect_bd_intf_net -intf_net S07_AXI_0_1 [get_bd_intf_ports S07_AXI_0] [get_bd_intf_pins ddr_subsystem/AI_S07_AXI]
  connect_bd_intf_net -intf_net axi_apb_bridge_1_APB_M [get_bd_intf_ports ai_cfg_apb_m] [get_bd_intf_pins axi_apb_bridge_1/APB_M]
  connect_bd_intf_net -intf_net axi_interconnect_0_M00_AXI [get_bd_intf_pins axi_apb_bridge_1/AXI4_LITE] [get_bd_intf_pins axi_interconnect_0/M00_AXI]
  connect_bd_intf_net -intf_net axi_interconnect_0_M01_AXI [get_bd_intf_pins axi_interconnect_0/M01_AXI] [get_bd_intf_pins ddr_subsystem/DDR4_MEM_CTRL_S00_AXI_0]
  connect_bd_intf_net -intf_net axi_interconnect_1_M00_AXI [get_bd_intf_pins axi_interconnect_1/M00_AXI] [get_bd_intf_pins ddr_subsystem/DDR4_MEM_S00_AXI]
  connect_bd_intf_net -intf_net ddr_subsystem_DDR4_MEM_C0 [get_bd_intf_ports c0_ddr4] [get_bd_intf_pins ddr_subsystem/DDR4_MEM_C0]
  connect_bd_intf_net -intf_net ddr_subsystem_DDR4_MEM_C1 [get_bd_intf_ports c1_ddr4] [get_bd_intf_pins ddr_subsystem/DDR4_MEM_C1]
  connect_bd_intf_net -intf_net ddr_subsystem_DDR4_MEM_C2 [get_bd_intf_ports c2_ddr4] [get_bd_intf_pins ddr_subsystem/DDR4_MEM_C2]
  connect_bd_intf_net -intf_net xdma_0_M_AXI [get_bd_intf_pins axi_interconnect_1/S00_AXI] [get_bd_intf_pins xdma_0/M_AXI]
  connect_bd_intf_net -intf_net xdma_0_pcie_mgt [get_bd_intf_ports pci_exp] [get_bd_intf_pins xdma_0/pcie_mgt]

  # Create port connections
  connect_bd_net -net ddr_subsystem_ddr4_init_calib_complete_c0 [get_bd_pins ddr_subsystem/ddr4_init_calib_complete_c0] [get_bd_pins xlconcat_0/In0]
  connect_bd_net -net ddr_subsystem_ddr4_init_calib_complete_c1 [get_bd_pins ddr_subsystem/ddr4_init_calib_complete_c1] [get_bd_pins xlconcat_0/In1]
  connect_bd_net -net ddr_subsystem_ddr4_init_calib_complete_c2 [get_bd_pins ddr_subsystem/ddr4_init_calib_complete_c2] [get_bd_pins xlconcat_0/In2]
  connect_bd_net -net hbm_100m_clk_mmcm_clk_out1 [get_bd_pins axi_interconnect_0/M01_ACLK] [get_bd_pins ddr_subsystem/DDR4_MEM_CTRL_S00_ACLK_0] [get_bd_pins hbm_100m_clk_mmcm/clk_out1] [get_bd_pins proc_sys_reset_0/slowest_sync_clk]
  connect_bd_net -net hbm_100m_clk_mmcm_locked [get_bd_pins hbm_100m_clk_mmcm/locked] [get_bd_pins proc_sys_reset_0/dcm_locked]
  connect_bd_net -net proc_sys_reset_0_interconnect_aresetn [get_bd_pins ddr_subsystem/DDR4_MEM_CTRL_S00_ARESETN_0] [get_bd_pins proc_sys_reset_0/interconnect_aresetn]
  connect_bd_net -net proc_sys_reset_0_peripheral_aresetn [get_bd_pins axi_interconnect_0/M01_ARESETN] [get_bd_pins proc_sys_reset_0/peripheral_aresetn]
  connect_bd_net -net reset_rtl_0_1 [get_bd_ports sys_rst_n] [get_bd_pins proc_sys_reset_0/aux_reset_in] [get_bd_pins util_vector_logic_0/Op1] [get_bd_pins xdma_0/sys_rst_n]
  connect_bd_net -net rst_clk_wiz_4_100M_peripheral_aresetn [get_bd_pins axi_apb_bridge_1/s_axi_aresetn] [get_bd_pins axi_interconnect_0/ARESETN] [get_bd_pins axi_interconnect_0/M00_ARESETN] [get_bd_pins axi_interconnect_0/S00_ARESETN] [get_bd_pins axi_interconnect_1/ARESETN] [get_bd_pins axi_interconnect_1/M00_ARESETN] [get_bd_pins axi_interconnect_1/S00_ARESETN] [get_bd_pins ddr_subsystem/DDR4_MEM_S00_ARESETN] [get_bd_pins ddr_subsystem/S01_ARESETN_0] [get_bd_pins ddr_subsystem/S02_ARESETN_0] [get_bd_pins ddr_subsystem/S03_ARESETN_0] [get_bd_pins ddr_subsystem/S04_ARESETN_0] [get_bd_pins ddr_subsystem/S05_ARESETN_0] [get_bd_pins ddr_subsystem/S06_ARESETN_0] [get_bd_pins ddr_subsystem/S07_ARESETN_0] [get_bd_pins hbm_100m_clk_mmcm/resetn] [get_bd_pins proc_sys_reset_0/ext_reset_in] [get_bd_pins util_vector_logic_1/Op1] [get_bd_pins xdma_0/axi_aresetn]
  connect_bd_net -net usr_irq_req_0_1 [get_bd_ports usr_irq_req_0] [get_bd_pins xdma_0/usr_irq_req]
  connect_bd_net -net util_ds_buf_0_IBUF_DS_ODIV2 [get_bd_pins pcie_ref_clk_buffer/IBUF_DS_ODIV2] [get_bd_pins xdma_0/sys_clk]
  connect_bd_net -net util_ds_buf_0_IBUF_OUT [get_bd_pins pcie_ref_clk_buffer/IBUF_OUT] [get_bd_pins xdma_0/sys_clk_gt]
  connect_bd_net -net util_vector_logic_0_Res [get_bd_pins ddr_subsystem/ddr4_sys_rst_c0] [get_bd_pins ddr_subsystem/ddr4_sys_rst_c1] [get_bd_pins ddr_subsystem/ddr4_sys_rst_c2] [get_bd_pins util_vector_logic_0/Res]
  connect_bd_net -net util_vector_logic_1_Res [get_bd_ports ai_rst] [get_bd_pins util_vector_logic_1/Res]
  connect_bd_net -net xdma_0_axi_aclk [get_bd_ports ai_clk_100mhz] [get_bd_pins axi_apb_bridge_1/s_axi_aclk] [get_bd_pins axi_interconnect_0/ACLK] [get_bd_pins axi_interconnect_0/M00_ACLK] [get_bd_pins axi_interconnect_0/S00_ACLK] [get_bd_pins axi_interconnect_1/ACLK] [get_bd_pins axi_interconnect_1/M00_ACLK] [get_bd_pins axi_interconnect_1/S00_ACLK] [get_bd_pins ddr_subsystem/DDR4_MEM_S00_ACLK] [get_bd_pins ddr_subsystem/S01_ACLK_0] [get_bd_pins ddr_subsystem/S02_ACLK_0] [get_bd_pins ddr_subsystem/S03_ACLK_0] [get_bd_pins ddr_subsystem/S04_ACLK_0] [get_bd_pins ddr_subsystem/S05_ACLK_0] [get_bd_pins ddr_subsystem/S06_ACLK_0] [get_bd_pins ddr_subsystem/S07_ACLK_0] [get_bd_pins hbm_100m_clk_mmcm/clk_in1] [get_bd_pins xdma_0/axi_aclk]
  connect_bd_net -net xlconcat_0_dout [get_bd_ports dout_0] [get_bd_pins xlconcat_0/dout]

  # Create address segments
  assign_bd_address -offset 0x00000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000200000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c1/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000400000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c2/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x00800000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs ai_cfg_apb_m/Reg] -force
  assign_bd_address -offset 0x00800000 -range 0x00100000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c0/C0_DDR4_MEMORY_MAP_CTRL/C0_REG] -force
  assign_bd_address -offset 0x00900000 -range 0x00100000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c1/C0_DDR4_MEMORY_MAP_CTRL/C0_REG] -force
  assign_bd_address -offset 0x00A00000 -range 0x00100000 -target_address_space [get_bd_addr_spaces xdma_0/M_AXI_LITE] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c2/C0_DDR4_MEMORY_MAP_CTRL/C0_REG] -force
  assign_bd_address -offset 0x00000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S01_AXI_1] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000200000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S01_AXI_1] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c1/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000400000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S01_AXI_1] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c2/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S02_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000200000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S02_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c1/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000400000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S02_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c2/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S03_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000200000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S03_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c1/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000400000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S03_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c2/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S04_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000200000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S04_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c1/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000400000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S04_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c2/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S05_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000200000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S05_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c1/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000400000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S05_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c2/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S06_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000200000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S06_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c1/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000400000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S06_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c2/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x00000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S07_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c0/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000200000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S07_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c1/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force
  assign_bd_address -offset 0x000400000000 -range 0x000100000000 -target_address_space [get_bd_addr_spaces S07_AXI_0] [get_bd_addr_segs ddr_subsystem/ddr4_mem_c2/C0_DDR4_MEMORY_MAP/C0_DDR4_ADDRESS_BLOCK] -force


  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_pcie_mem()
cr_bd_pcie_mem ""
set_property REGISTERED_WITH_MANAGER "1" [get_files pcie_mem.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files pcie_mem.bd ] 
##
##set idrFlowPropertiesConstraints ""
##catch {
## set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
## set_param runs.disableIDRFlowPropertyConstraints 1
##}
##
### Create 'synth_1' run (if not found)
##if {[string equal [get_runs -quiet synth_1] ""]} {
##    create_run -name synth_1 -part xcvu37p-fsvh2892-2L-e -flow {Vivado Synthesis 2020} -strategy "Flow_PerfOptimized_high" -report_strategy {No Reports} -constrset constrs_1
##} else {
##  set_property strategy "Flow_PerfOptimized_high" [get_runs synth_1]
##  set_property flow "Vivado Synthesis 2020" [get_runs synth_1]
##}
##set obj [get_runs synth_1]
##set_property set_report_strategy_name 1 $obj
##set_property report_strategy {Vivado Synthesis Default Reports} $obj
##set_property set_report_strategy_name 0 $obj
### Create 'synth_1_synth_report_utilization_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
##  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
##}
##set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
##if { $obj != "" } {
##
##}
##set obj [get_runs synth_1]
##set_property -name "auto_incremental_checkpoint.directory" -value "/data/disk0/wrk/OpenTF/f37x-2025-05-08-15_38_07-250m-1core.srcs/utils_1/imports/synth_1" -objects $obj
##set_property -name "strategy" -value "Flow_PerfOptimized_high" -objects $obj
##set_property -name "steps.synth_design.args.directive" -value "PerformanceOptimized" -objects $obj
##set_property -name "steps.synth_design.args.fsm_extraction" -value "one_hot" -objects $obj
##set_property -name "steps.synth_design.args.keep_equivalent_registers" -value "1" -objects $obj
##set_property -name "steps.synth_design.args.resource_sharing" -value "off" -objects $obj
##set_property -name "steps.synth_design.args.no_lc" -value "1" -objects $obj
##set_property -name "steps.synth_design.args.shreg_min_size" -value "5" -objects $obj
##
### set the current synth run
##current_run -synthesis [get_runs synth_1]
##
### Create 'impl_1' run (if not found)
##if {[string equal [get_runs -quiet impl_1] ""]} {
##    create_run -name impl_1 -part xcvu37p-fsvh2892-2L-e -flow {Vivado Implementation 2020} -strategy "Congestion_SSI_SpreadLogic_high" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
##} else {
##  set_property strategy "Congestion_SSI_SpreadLogic_high" [get_runs impl_1]
##  set_property flow "Vivado Implementation 2020" [get_runs impl_1]
##}
##set obj [get_runs impl_1]
##set_property set_report_strategy_name 1 $obj
##set_property report_strategy {UltraFast Design Methodology Reports} $obj
##set_property set_report_strategy_name 0 $obj
### Create 'impl_1_init_report_timing_summary_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
##  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
##if { $obj != "" } {
##set_property -name "options.max_paths" -value "10" -objects $obj
##
##}
### Create 'impl_1_init_report_utilization_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_utilization_0] "" ] } {
##  create_report_config -report_name impl_1_init_report_utilization_0 -report_type report_utilization:1.0 -steps init_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_utilization_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_init_report_high_fanout_nets_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_high_fanout_nets_0] "" ] } {
##  create_report_config -report_name impl_1_init_report_high_fanout_nets_0 -report_type report_high_fanout_nets:1.0 -steps init_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_high_fanout_nets_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_init_report_control_sets_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_control_sets_0] "" ] } {
##  create_report_config -report_name impl_1_init_report_control_sets_0 -report_type report_control_sets:1.0 -steps init_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_control_sets_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_opt_report_drc_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
##  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_opt_report_utilization_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_utilization_0] "" ] } {
##  create_report_config -report_name impl_1_opt_report_utilization_0 -report_type report_utilization:1.0 -steps opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_utilization_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_opt_report_methodology_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_methodology_0] "" ] } {
##  create_report_config -report_name impl_1_opt_report_methodology_0 -report_type report_methodology:1.0 -steps opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_methodology_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_opt_report_timing_summary_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
##  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
##if { $obj != "" } {
##set_property -name "options.max_paths" -value "10" -objects $obj
##
##}
### Create 'impl_1_opt_report_high_fanout_nets_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_high_fanout_nets_0] "" ] } {
##  create_report_config -report_name impl_1_opt_report_high_fanout_nets_0 -report_type report_high_fanout_nets:1.0 -steps opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_high_fanout_nets_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_opt_report_control_sets_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_control_sets_0] "" ] } {
##  create_report_config -report_name impl_1_opt_report_control_sets_0 -report_type report_control_sets:1.0 -steps opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_control_sets_0]
##if { $obj != "" } {
##set_property -name "options.verbose" -value "1" -objects $obj
##
##}
### Create 'impl_1_opt_report_design_analysis_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_design_analysis_0] "" ] } {
##  create_report_config -report_name impl_1_opt_report_design_analysis_0 -report_type report_design_analysis:1.0 -steps opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_design_analysis_0]
##if { $obj != "" } {
##set_property -name "options.logic_level_distribution" -value "1" -objects $obj
##
##}
### Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
##  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
##if { $obj != "" } {
##set_property -name "options.max_paths" -value "10" -objects $obj
##
##}
### Create 'impl_1_place_report_io_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
##  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_place_report_utilization_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
##  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
##  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_place_report_timing_summary_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
##  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
##if { $obj != "" } {
##set_property -name "options.max_paths" -value "10" -objects $obj
##
##}
### Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
##  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
##if { $obj != "" } {
##set_property -name "options.max_paths" -value "10" -objects $obj
##
##}
### Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
##  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
##if { $obj != "" } {
##set_property -name "options.max_paths" -value "10" -objects $obj
##
##}
### Create 'impl_1_route_report_clock_utilization_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
##  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_route_report_drc_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
##  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_route_report_power_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
##  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_route_report_route_status_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
##  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_route_report_timing_summary_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
##  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
##if { $obj != "" } {
##set_property -name "options.max_paths" -value "10" -objects $obj
##set_property -name "options.warn_on_violation" -value "1" -objects $obj
##
##}
### Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
##  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
##if { $obj != "" } {
##
##}
### Create 'impl_1_route_report_bus_skew_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
##  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
##if { $obj != "" } {
##set_property -name "options.warn_on_violation" -value "1" -objects $obj
##
##}
### Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
##  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
##if { $obj != "" } {
##set_property -name "options.max_paths" -value "10" -objects $obj
##set_property -name "options.warn_on_violation" -value "1" -objects $obj
##
##}
### Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
##if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
##  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
##}
##set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
##if { $obj != "" } {
##set_property -name "options.warn_on_violation" -value "1" -objects $obj
##
##}
##set obj [get_runs impl_1]
##set_property -name "auto_rqs.directory" -value "/data/disk0/wrk/OpenTF/f37x-2025-05-08-15_38_07-250m-1core.srcs/utils_1/imports/impl_1" -objects $obj
##set_property -name "auto_incremental_checkpoint.directory" -value "/data/disk0/wrk/OpenTF/f37x-2025-05-08-15_38_07-250m-1core.srcs/utils_1/imports/impl_1" -objects $obj
##set_property -name "strategy" -value "Congestion_SSI_SpreadLogic_high" -objects $obj
##set_property -name "steps.place_design.args.directive" -value "SSI_SpreadLogic_high" -objects $obj
##set_property -name "steps.phys_opt_design.args.directive" -value "AggressiveExplore" -objects $obj
##set_property -name "steps.route_design.args.directive" -value "AlternateCLBRouting" -objects $obj
##set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
##set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj
##
### set the current impl run
##current_run -implementation [get_runs impl_1]
##catch {
## if { $idrFlowPropertiesConstraints != {} } {
##   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
## }
##}
##
##puts "INFO: Project created:${_xil_proj_name_}"
### Create 'drc_1' gadget (if not found)
##if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
##create_dashboard_gadget -name {drc_1} -type drc
##}
##set obj [get_dashboard_gadgets [ list "drc_1" ] ]
##set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj
##
### Create 'methodology_1' gadget (if not found)
##if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
##create_dashboard_gadget -name {methodology_1} -type methodology
##}
##set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
##set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj
##
### Create 'power_1' gadget (if not found)
##if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
##create_dashboard_gadget -name {power_1} -type power
##}
##set obj [get_dashboard_gadgets [ list "power_1" ] ]
##set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj
##
### Create 'timing_1' gadget (if not found)
##if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
##create_dashboard_gadget -name {timing_1} -type timing
##}
##set obj [get_dashboard_gadgets [ list "timing_1" ] ]
##set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj
##
### Create 'utilization_1' gadget (if not found)
##if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
##create_dashboard_gadget -name {utilization_1} -type utilization
##}
##set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
##set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
##set_property -name "run.step" -value "synth_design" -objects $obj
##set_property -name "run.type" -value "synthesis" -objects $obj
##
### Create 'utilization_2' gadget (if not found)
##if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
##create_dashboard_gadget -name {utilization_2} -type utilization
##}
##set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
##set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj
##
##move_dashboard_gadget -name {utilization_1} -row 0 -col 0
##move_dashboard_gadget -name {power_1} -row 1 -col 0
##move_dashboard_gadget -name {drc_1} -row 2 -col 0
##move_dashboard_gadget -name {timing_1} -row 0 -col 1
##move_dashboard_gadget -name {utilization_2} -row 1 -col 1
##move_dashboard_gadget -name {methodology_1} -row 2 -col 1


# Launch Synthesis
set_property strategy "Flow_PerfOptimized_high" [get_runs synth_1]

set_property report_strategy {UltraFast Design Methodology Reports} [get_runs impl_1]
set_property strategy Congestion_SSI_SpreadLogic_high [get_runs impl_1]


launch_runs synth_1 -jobs 8
wait_on_run synth_1


launch_runs impl_1 -jobs  8
wait_on_run impl_1

launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1


puts "INFO: Project dir:${_xil_proj_name_}"

set bit_file "./${_xil_proj_name_}/${_xil_proj_name_}.runs/impl_1/f37x_top.bit" 
set mcs_file "./${_xil_proj_name_}/f37x_top.mcs" 

puts "INFO: bit file:${bit_file}"
puts "INFO: mcs file:${mcs_file}"

##write_cfgmem  -format mcs -size 128 -interface SPIx4 -loadbit {up 0x00000000 ${bit_file} } -file ${mcs_file} -force
write_cfgmem  -format mcs -size 128 -interface SPIx4 -loadbit "up 0x00000000 ${bit_file}" -file ${mcs_file} -force



exit






